server:
  port: 8080
spring:
  data:
    mongodb:
      port: 27017
      username: root
      password: root
      host: localhost
      database: admin
  cloud:
    kubernetes:
      enabled: false
      config:
        enabled: false
